FROM node:16 as build
WORKDIR /app
COPY package.json .
RUN yarn install --silent
COPY . .
RUN yarn run build
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]