version: '3.5'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    ports:
      - '3001:3001'
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - '27017:27017'
    command: mongod --noauth > /dev/null 2>&1
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
