version: '3.5'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/app
    ports:
      - '3001:3001'
