version: '3.5'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - ./frontend/.env.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/:/app
      - /app/node_modules
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - ./backend/.env.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - '3001:3001'
